### ISSUE TITLE
Building fails on Windows 10

### ISSUE THREAD

**Issue by ohenley** [onox/orka#10]
Along the way you should cross the following:

- orka_test-test_6_gltf.adb:195:28: prefix of "Access" attribute must be aliased

- orka-loops.ads:59:41: internal call cannot appear in precondition of protected o                                         peration

- orka-simd-sse4_1-doubles-math.ads:26:7: error: '.builtin_ia32_roundpd' nee                                                                         ds isa option -m32 -msse4.1

- orka-atomics.ads:24:13: error: inlining failed in call to always_inline 'Orka.Atomics.Decrement': function                                     body not available. (note: Did not find proper fix yet.)

 I let go even though it looks interesting.

**Comment by onox** [comment]
Thanks for creating this issue. I have access to a W10 machine, but I've never bothered/tried to build it on Windows. Did you use GNAT 2017?

**Comment by ohenley** [comment]
Hey! yes I used GNAT 2017.

**Comment by onox** [comment]
Hi @ohenley, a couple of months have passed, but could you try again? :smile: The project should now compile with at least GNAT CE 2018. Make sure to update json-ada.

I got a linker error though about `wglGetProcAddress`. I fixed this by changing it to `GetProcAddress` in `src/gl/windows/gl-loader.ads`. (Not committed because it might be a driver issue).

I got another linker error about all the `glfw*` functions. I tried copying `glfw3.dll` to all the possible file locations of GNAT, but that didn't seem to fix it. I'm not familiar with Windows (10), so maybe you manage to fix it.

**Comment by ohenley** [comment]
Sure! Great news!
I'll try to give a run this week. I keep you post.

Olivier

**Comment by ohenley** [comment]
Hi onox,

ok, I am on a brand new Windows 10 machine, using GNAT CE 2018 and run into
problems. (Me too, re-installing the glfw libs for the gnat linker to pick
it is not straight forward at all. Even choosing the right lib version is
sketchy... now where to place them is like a guess game.)

 1. I cant seem to get around your json-ada dependency. IMO both readmes
are too thin in that regard.

eg. If I do in json-ada

make PREFIX=C:/foo/bar install

then move to orka an do

make PREFIX=C:/foo/bar

I get the following:

gprbuild -dm -p -XWindowing_System=windows -XLibrary_Type=relocatable
-XCompiler_Flags="-O2 -march=native" -XMode=development -P orka-glfw.gpr
-largs -Wl,-z,relro -Wl,-z,now
orka.gpr:2:06: unknown project file: "json_ada"
orka.gpr:2:06: imported by
"C:\Users\olivier\Desktop\perso\Ada\orka\orka.gpr"
orka.gpr:2:06: imported by
"C:\Users\olivier\Desktop\perso\Ada\orka\orka-glfw.gpr"
gprbuild: "orka-glfw.gpr" processing failed
make.exe": *** [build_src] Error 4

As you can see, json_ada is not found. Then I tried to set the absolute
path in orka.gpr --> with "C:/foo/bar/share/gpr/json_ada.gpr"
and its ok. So I am missing something for sure. Maybe it could be a good
idea to exemplify this in the readmes.

2. I get the wglGetProcAddress linking problem too. You should check what
Felix changed regarding that because I just compiled its latest github
OpenGLAda and had no problem. I checked and he handles this whole wgl a bit
different with providing gl-wgl.ads and the signature inside
gl-api-subprogram_reference is different that yours in gl-loader.

Let me know of any findings. I'll give another try later.

Olivier




On Fri, Aug 17, 2018 at 3:06 PM onox <notifications@github.com> wrote:
>
> Hi @ohenley, a couple of months have passed, but could you try again? The
project should now compile with at least GNAT CE 2018. Make sure to update
json-ada.
>
> I got a linker error though about wglGetProcAddress. I fixed this by
changing it to GetProcAddress in src/gl/windows/gl-loader.ads. (Not
committed because it might be a driver issue).
>
> I got another linker error about all the glfw* functions. I tried copying
glfw3.dll to all the possible file locations of GNAT, but that didn't seem
to fix it. I'm not familiar with Windows (10), so maybe you manage to fix
it.

**Comment by ohenley** [comment]
About json-ada. Why dont you put it as a git submodule of orka?

**Comment by onox** [comment]
> then move to orka an do
>
> make PREFIX=C:/foo/bar

PREFIX is only used when installing Orka (to a location where the user has write access). It's not used during the compilation step. Whether gprbuild can find json-ada depends on GNAT CE's project search paths. I think you can see this on Windows as well with `gnatls -v`.

> As you can see, json_ada is not found. Then I tried to set the absolute path in orka.gpr --> with "C:/foo/bar/share/gpr/json_ada.gpr" and its ok. So I am missing something for sure. Maybe it could be a good idea to exemplify this in the readmes.

I'll try to improve the instructions in `README.md` a bit by mentioning the project search path.

>Why dont you put it as a git submodule of orka?

I don't like git submodules that much.

> (Me too, re-installing the glfw libs for the gnat linker to pick it is not straight forward at all. Even choosing the right lib version is sketchy... now where to place them is like a guess game.)

Where did you end up installing glfw3.dll?

**Comment by ohenley** [comment]
Ok, on my side building using GNAT CE 2018 I get 'duplicate' error caused the config.gpr in json-ada and config.gpr in orka:

config.gpr:15:18: duplicate project name "config"
config.gpr:15:18: already in "...\json-ada\config.gpr"

I asked on SO about it because maybe I was missing something on how to make this config work but i looks like it should not:

https://stackoverflow.com/questions/53281765/with-in-duplicate-gprbuild-name-files?noredirect=1#comment93454595_53281765

How do you go about it? Thx.

**Comment by ohenley** [comment]
Works! But now, like so, I stuck at the link error about wglGetProcAddress

**Comment by onox** [comment]
I just tried building it again in GPS:

1. Make sure you `git pull` to get the latest commits.

2. Open `tools.gpr` and check that GPS properly switches to this .gpr file

3. Copy `glfw3.dll` from [64-bit Windows binaries](https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.bin.WIN64.zip) to the git repository.

4. In GPS in the Scenario tab, set Build Mode to "default", Windowing_System to "windows", and "Library_Type" to "static" (with "relocatable" I had problems that I had to copy the .dll's to the `bin/` folder or that I got a link error about wglGetProcAddress)

5. If GNAT complains about SSE4.1, then you need to set "-O2 -march=native" as the compiler switches. For it didn't work to set them in the Compiler_Flags scenario variable, instead I added them to `Compiler_Switches` in `config.gpr`.

6. If GNAT still complains about missing `-lglfw3`, then you need to add `with "glfw";` to `orka-glfw.gpr` and create the file `glfw.gpr` in the git repository:

```ada
library project GLFW is

   for Source_Files use ();

   for Library_Dir use ".";
   for Library_Name use "glfw3";
   for Library_Kind use "relocatable";

   for Externally_Built use "true";

end GLFW;
```

7. Build via Build > Project > Build All. Enable "Create object dirs".

8. Try to run `orka-info` from GPS via Build > Run > orka-info.adb

Note 1: For me creating `glfw.gpr` and adding `glfw3.dll` from the 64-bit glfw Windows binaries was needed to get GLFW to link.

Note 2: I had to set Library_Type (in scenario tab) to "static" to get it to link with wglGetProcAddress. Maybe GetProcAddress may have also worked. With "relocatable" GPS couldn't find the .dll files it has built seconds ago, so then I would need to copy `liborka.dll` and `liborka-glfw.dll` to the `bin/` folder.

Note 3: When I got `orka-info` to run, I got a Constraint_Error "access check failed" in `gl-runtime_loading.adb`. This means that GL couldn't find the OpenGL function. This happened with the `glCreate*` functions which are from 4.5. Even when I request a 4.5 context. I didn't check yet whether other (older) functions fail too. This is with Intel drivers which say it supports 4.5.

**Comment by onox** [comment]
@ohenley What GPU do you have btw? Intel, AMD, Nvidia?

**Comment by onox** [comment]
I've fixed the problem with `wglGetProcAddress`: it returns null for OpenGL 1.1 functions, so the code will now fallback to `GetProcAddress` if the previous function returns null.

Also fixed creating the default framebuffer, renderbuffer, vertex array object, and feedback object.

**Comment by ohenley** [comment]
1. I was able to build tools.gpr on Windows10.

- Exact same steps until linking glfw3
- For glfw3 to link I did not create a glfw.gpr file etc. What I did is install libglfw3ddl.a to MY_GNAT_CE_INSTALL/2018/bin/ and in orka-glfw.gpr change the linker option from "-lglfw3" to "-lglfw3dll"

2. My GPU is an integrated intel (Acer laptop)

**Comment by ohenley** [comment]
But this:

$ ./orka-gltf.exe ./models busterDrone.gltf
Flushing 0 messages in the debug log:
Set callback for debug messages
[19:59:05.788891 HIGH] [SHADER_COMPILER:ERROR] 0: SHADER_ID_COMPILE error has be                                    en generated. GLSL compile failed for shader 1, "": ERROR: 0:10: 'restrict' : sy                                    ntax error syntax error
Error: raised ORKA.RENDERING.PROGRAMS.MODULES.SHADER_COMPILE_ERROR : shaders/too                                    ls/gltf.vert:ERROR: 0:10: 'restrict' : syntax error syntax error


Call stack traceback locations:
0x5cc3b4 0x5d0fce 0x41109d 0x67da3c 0x4013b3 0x4014e6 0x7ffc974e3032 0x7ffc979b1                                    46f

[19:59:05.799851 DEBUG] [OTHER] 0: Shutting down GLFW

Maybe it would be a good idea to provide a working gltf model

**Comment by ohenley** [comment]
examples.gpr builds too. Here are the exe that does not work:

$ ./gl_test-subroutines.exe
Listing shaders attached to program...
  Kind: VERTEX_SHADER
  Status: TRUE
  Kind: FRAGMENT_SHADER
  Status: TRUE
Loaded shaders
Loaded data
Subroutines:
  Functions:  2
  Uniforms:  1
  Function length:  8
  Uniform length:  13
Name function 0: update_x
Name uniform 0: update_pos[0]

Execution of C:\Users\olivier\Desktop\perso\Ada\orka\bin\gl_test-subroutines.exe terminated by unhandled exception
raised GL.OBJECTS.PROGRAMS.SUBROUTINE_INACTIVE_ERROR : Subroutine update_z is inactive (unused)
Call stack traceback locations:
0x47535b 0x402692 0x4c70fc 0x4013b3 0x4014e6 0x7ffc974e3032 0x7ffc979b146f

------------------------------

$ ./orka_test-test_10_compute.exe
Flushing 0 messages in the debug log:
Set callback for debug messages
[20:11:18.918926 HIGH] [SHADER_COMPILER:ERROR] 0: SHADER_ID_COMPILE error has been generated. GLSL compile failed for shader 1, "": ERROR: 0:9: '#extension' :  'GL_ARB_shader_ballot' is not supported
ERROR: 0:15: 'buffer' : syntax error syntax error
[20:11:18.922346 DEBUG] [OTHER] 0: Shutting down GLFW

Execution of C:\Users\olivier\Desktop\perso\Ada\orka\bin\orka_test-test_10_compute.exe terminated by unhandled exception
raised ORKA.RENDERING.PROGRAMS.MODULES.SHADER_COMPILE_ERROR : test-10-module-1.comp:ERROR: 0:9: '#extension' :  'GL_ARB_shader_ballot' is not supported
ERROR: 0:15: 'buffer' : syntax error syntax error


Call stack traceback locations:
0x4ce404 0x4d309f 0x401878 0x5160dc 0x4013b3 0x4014e6 0x7ffc974e3032 0x7ffc979b146f

**Comment by onox** [comment]
Hi, with the Intel drivers on Windows I get these GLSL errors as well. In the shaders you need to replace `#version 330 core` with `#version 450 core`. For `orka-info` you need to modify `tools/orka_info.adb` line 25.

I don't know if this issue happens just with Intel on Windows, or whether it happens with AMD and Nvidia as well. I could set the versions to 4.5, but that would force Intel Ivy Bridge users on Linux to override the Mesa version. (They have 4.2 + 99 % of the extensions of 4.3 to 4.6).

**Comment by onox** [comment]
The glTF loader is not that flexible and has some ugly code (procedures `Count_Parts` and `Add_Parts` in `Orka.Resources.Models.glTF`).

The glTF model needs to have 3 attributes (position, vertex, and UV attribute) and only 1 primitive per mesh part (meaning, the index type needs to be sufficiently large for the biggest mesh part).

I'll try to find some public .gltf models that work out of the box and list them here.

**Comment by onox** [comment]
@ohenley I've found a model that works:

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/DamagedHelmet/glTF

Download the .bin and the .gltf files. You may need to adjust `Light_Position` in `tools/orka_gltf.adb` on line 57.

**Comment by onox** [comment]
Closing this stale issue. With a bit of luck the crates should link with EGL on the msys2 platform and a surfaceless EGL context can be used. Someone contributing a win32 backend to AWT is still appreciated.
