### ISSUE TITLE
Build fails on systems that do not have a CPU with AVX2 or FMA

### ISSUE THREAD

**Issue by Rodeo-McCabe** [onox/orka#58]
Manjaro Linux  
x86_64, Intel i5

When first building with `make` the following errors were produced (output edited for brevity):

    orka-simd-fma-singles-arithmetic.adb: In function 'Orka.Simd.Fma.Singles.Arithmetic."*"':  
    error: ‘.builtin_ia32_vfmaddps’ needs isa option -mfma -mfma4
    orka-simd-fma-doubles-arithmetic.adb: In function ‘Orka.Simd.Fma.Doubles.Arithmetic."*"’:  
    error: ‘.builtin_ia32_permdf256’ needs isa option -mavx2  
    error: ‘.builtin_ia32_vfmaddpd256’ needs isa option -mfma -mfma4

I added the arguments `-mavx2 -mfma -mfma4` to the `CFLAGS` variable in the Makefile. This caused compilation to go a little further, and when it failed only the `Singles` file produced errors. Further minor twiddling with the Makefile has produced no results for me.

**Comment by onox** [comment]
Which CPU do you have exactly? Try `lscpu | grep name`.

**Comment by Rodeo-McCabe** [comment]
`Model name:                      Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz`

Anything else I can do to help please let me know. This project is awesome and I'm really looking forward to tinkering with it. Thanks for all your work on it.

**Comment by onox** [comment]
3xxx is indeed Ivy Bridge, which does not have AVX2 or FMA. I'll try to make these optional and put it behind some build flag.

In the mean type you can just delete the packages that use AVX2 and FMA. `git grep AVX2 -- src` and `git grep FMA -- src` will show the files.

**Comment by Rodeo-McCabe** [comment]
Thanks, that worked and I have the examples running. For future reference, here is a one-liner to delete the files in question: `find . | grep fma | xargs rm && find . | grep avx2 | xargs rm`

The website says Ivy Bridge CPUs are supported, perhaps there should be a note about this there.
