### ISSUE TITLE
Prefer if expression

### ISSUE THREAD

**Issue by pjljvandelaar** [onox/orka#87]
Dear Developers,

There are many places where if expressions could be used.
I don't know whether you consider that an improvement in readability.
But I think that in orka/src/gl/implementation/gl-objects-textures.adb the following change
```diff
-      if Object.Compressed then
-         return Object.Create_View
-          (Kind      => Kind,
-           Format    => Object.Compressed_Format,
-           Min_Level => Object.Lowest_Mipmap_Level,
-           Levels    => Object.Mipmap_Levels,
-           Min_Layer => Layer,
-           Layers    => Get_Layers (Kind));
-      else
-         return Object.Create_View
-          (Kind      => Kind,
-           Format    => Object.Internal_Format,
-           Min_Level => Object.Lowest_Mipmap_Level,
-           Levels    => Object.Mipmap_Levels,
-           Min_Layer => Layer,
-           Layers    => Get_Layers (Kind));
-      end if;
+         return Object.Create_View
+          (Kind      => Kind,
+           Format    => (if Object.Compressed then Object.Compressed_Format else Object.Internal_Format),
+           Min_Level => Object.Lowest_Mipmap_Level,
+           Levels    => Object.Mipmap_Levels,
+           Min_Layer => Layer,
+           Layers    => Get_Layers (Kind));
``` 
improves readability.

See patch file for more inspiration of places where code might be simplified.
[If_Expression.zip](https://github.com/onox/orka/files/10696434/If_Expression.zip)

Greetings,
 Pierre

**Comment by pjljvandelaar** [comment]
I am missing the change in orka/src/gl/implementation/gl-objects-textures.adb as shown above.
Why don't you think it is an improvement?

**Comment by onox** [comment]
Because there are 2 definitions of `Create_View`, each specifying a different type (compressed or uncompressed). I find it a bit ugly. Perhaps it would be better to use a subtype for the compressed textures, so that only 1 definition of `Create_View` is needed.
