### ISSUE TITLE
What's reusable for OpenGL 3.3?

### ISSUE THREAD

**Issue by HROMANO** [onox/orka#88]
Hi,

I only have an opengl 3.3 graphic card. Are there parts of orka that I could still use? And which part are 4.6 only?

Thanks

**Comment by onox** [comment]
Do you have some very old graphics card (before 2012) or from some unusual vendor (not from team green/blue/red) if it only supports up to 3.3? :thinking:

The most important extensions are listed on the [Installation](https://orka-engine.netlify.app/installation/#dependencies) page in the docs. On an old Intel Ivy Bridge GPU (generation 7) these are all supported with the latest [Mesa](https://mesamatrix.net/) driver (even when the driver gives you an OpenGL 4.2 rendering context). On older generations, extensions like ARB_compute_shader, ARB_multi_draw_indirect, and ARB_shader_storage_buffer_object might be missing (especially the latter is really needed for buffers).

The best thing to do would be to run `make tools` and then run `./orka_tools/build/bin/orka_info`. This will print the OpenGL version, driver, and the supported extensions.

Afterwards, run `make examples`, `cd examples`, and then see if you can run some of the examples like `./build/bin/orka_1_triangle`.

On Linux you can do rendering on the CPU with drivers like llvmpipe by prepending `MESA_LOADER_DRIVER_OVERRIDE=llvmpipe ` to the previously mentioned tools and examples.

Also be aware that some crates like `orka_simd`, `orka_transforms`, and `orka_tensors_cpu` do not depend on the `orka_opengl` crate, thus you can use them without a GPU.

**Comment by HROMANO** [comment]
Thank you for your reply,

It's an old computer + old graphic card (I built it around 2007 I think), but still fully operational (just can't read 4k films on it as it's too slow :-> but everything else is ok).

I will try your suggestions, in particular with CPU rendering.

**Comment by HROMANO** [comment]
Just for the record, I can build the tools but they crash at runtime (with or without MESA_LOADER…):

```
[./orka_tools/build/bin/orka_info]
0x55c72d0ee216 system__interrupt_management__notify_exception at ???
[/usr/lib/libc.so.6]
0x7f32a02e1f4e
[./orka_tools/build/bin/orka_info]
0x55c72d0d3483 gl__objects__buffers___elabs at ???
0x55c72d0a12e5 Adainit.Part at b__orka_info.adb:666
0x55c72d09ff22 Main at b__orka_info.adb:496
[/usr/lib/libc.so.6]
0x7f32a02cc78e
0x7f32a02cc848
[./orka_tools/build/bin/orka_info]
0x55c72d09ff93 _start at ???
0xfffffffffffffffe
```

Thank you anyway.

**Comment by onox** [comment]
Which OS and compiler did you use?

**Comment by HROMANO** [comment]
I'm on archlinux with gcc-ada 12.2.1
